spring.application.name=integration-bridge


# RabbitMQ connection
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

# Odoo config
odoo.url=${ODOO_URL}
odoo.db=${ODOO_DB}
odoo.userId=${ODOO_USER_ID}
odoo.apiKey=${ODOO_API_KEY}

# FossBilling config
fossbilling.url=${FOSSBILLING_URL}
fossbilling.apiKey=${FOSSBILLING_API_KEY}

# SendGrid config
sendgrid.apiKey=${SENDGRID_API_KEY}
sendgrid.fromEmail=${SENDGRID_FROM_EMAIL}

# Firebase
firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH:classpath:firebase-key.json}
