<<<<<<< HEAD
spring.application.name=integration-bridge


# RabbitMQ connection
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASS}

# Odoo config
odoo.url=http://localhost:30002
odoo.db=integration-group1
odoo.apiKey=9ffbfd7b980bc05ccb1431ae4a866f82d39e4e0d
odoo.user=admin@group1-integration.local

# FossBilling config
fossbilling.url=${FOSSBILLING_URL}
fossbilling.apiKey=${FOSSBILLING_API_KEY}

# SendGrid config
sendgrid.apiKey=${SENDGRID_API_KEY}
sendgrid.fromEmail=${SENDGRID_FROM_EMAIL}
=======
# RabbitMQ Connection Settings (From your Team Guide Section 5.3)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=30000
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

# Odoo Server Settings
server.port=8080
>>>>>>> feature-odoo-xml-delivery
